name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hey, this package is discontinued, Please check https://github.com/SebastienBtr/Dash-Chat-2 instead"
        pr-message: "Hey, this package is discontinued, please check https://github.com/SebastienBtr/Dash-Chat-2 instead"
